[tool.pyright]
reportIncompatibleVariableOverride = "none"
reportAttributeAccessIssue = "none"

[tool.isort]
profile = "black"
line_length = 110
skip_gitignore = true

[tool.black]
line-length = 110
target-version = ["py311"]
include = '''
(
    \.pyi?$
)
'''

[tool.djlint]
profile = "django"
# files = [
#     "path/to/templates/",
# ]
ignore = "H006,H030,H031"
close_void_tags = true
indent = 2
max_blank_lines = 1
max_line_length = 100
# blank_line_before_tag = "load,extends,include,block"
# blank_line_after_tag = "load,extends,include,endblock"
